[package]
name = "braindrain-web"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
askama = "0.14.0"
axum = "0.8.8"
braindrain-core = { path = "../../crates/core" }
braindrain-daemon = { path = "../../crates/daemon" }
serde.workspace = true
time.workspace = true
tokio = { workspace = true, features = ["net", "signal"] }
