[package]
name = "braindrain-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "braindrain"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
braindrain-service = { path = "../service" }
clap = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
